// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCexm8zJ5kvd6dB8VgGTDaZvCke2dekq8Y',
    appId: '1:548324169121:web:c35092b51bb8e3db5fe7e0',
    messagingSenderId: '548324169121',
    projectId: 'project-timowenz',
    authDomain: 'project-timowenz.firebaseapp.com',
    storageBucket: 'project-timowenz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXHBvlWLToTWMFTI_5jVv3fpkv2UlgJKY',
    appId: '1:548324169121:android:ad369b47eb89d1215fe7e0',
    messagingSenderId: '548324169121',
    projectId: 'project-timowenz',
    storageBucket: 'project-timowenz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjXBT7YCgFYi0OjulWd8N_AlLgYSCrZTI',
    appId: '1:548324169121:ios:2cc4373a8a93a6c85fe7e0',
    messagingSenderId: '548324169121',
    projectId: 'project-timowenz',
    storageBucket: 'project-timowenz.appspot.com',
    iosBundleId: 'com.example.ankiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjXBT7YCgFYi0OjulWd8N_AlLgYSCrZTI',
    appId: '1:548324169121:ios:dc56623c51bdad975fe7e0',
    messagingSenderId: '548324169121',
    projectId: 'project-timowenz',
    storageBucket: 'project-timowenz.appspot.com',
    iosBundleId: 'com.example.ankiapp.RunnerTests',
  );
}
